export enum NotificationType {
	BOOKING_CONFIRMATION,
	BOOKING_REMINDER,
	BOOKING_CANCELLATION,
	PAYMENT_CONFIRMATION,
	PAYMENT_DUE ,
	VEHICLE_MAINTENANCE,
	VEHICLE_AVAILABLE,
	DRIVER_ASSIGNMENT,
	ACCOUNT_UPDATE,
	SYSTEM_NOTIFICATION
}