export enum VehicleStatus {
	AVAILABLE = "AVAILABLE",
	BOOKED = "BOOKED",
	MAINTENANCE = "MAINTENANCE",
	RENTED = "RENTED",
	OUT_OF_SERVICE = "OUT_OF_SERVICE",
	BLOCKED = "BLOCKED",
	UNKNOWN = "UNKNOWN"
}

